package com.smartcampus.service;

import com.smartcampus.dto.request.ManagerBroadcastNoticeRequest;
import com.smartcampus.dto.response.ManagerBroadcastNoticeResponse;
import com.smartcampus.dto.response.NotificationResponse;
import com.smartcampus.entity.Booking;
import com.smartcampus.entity.BookingStatus;
import com.smartcampus.entity.Notification;
import com.smartcampus.entity.NotificationType;
import com.smartcampus.entity.Resource;
import com.smartcampus.entity.Role;
import com.smartcampus.entity.User;
import com.smartcampus.repository.BookingRepository;
import com.smartcampus.repository.NotificationRepository;
import com.smartcampus.repository.ResourceRepository;
import com.smartcampus.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class NotificationService {

    private final NotificationRepository notificationRepository;
    private final UserRepository userRepository;
    private final BookingRepository bookingRepository;
    private final ResourceRepository resourceRepository;


    // Get all notifications for a user (personal + role-based)
    public List<NotificationResponse> getNotificationsForUser(String userId, String role) {
        List<Notification> personal = notificationRepository
            .findByRecipientUserIdOrderByCreatedAtDesc(userId);

        List<Notification> roleBased = notificationRepository
            .findByTargetRoleOrderByCreatedAtDesc(role);

        // Merge, remove duplicates, sort by date
        return java.util.stream.Stream.concat(personal.stream(), roleBased.stream())
            .distinct()
            .sorted((a, b) -> b.getCreatedAt().compareTo(a.getCreatedAt()))
            .map(this::toDto)
            .collect(Collectors.toList());
    }

    // Count unread for badge
    public long getUnreadCount(String userId, String role) {
        long personal  = notificationRepository.countByRecipientUserIdAndReadFalse(userId);
        long roleBased = notificationRepository.countByTargetRoleAndReadFalse(role);
        return personal + roleBased;
    }

    // Mark single notification as read
    public NotificationResponse markAsRead(String notificationId, String userId) {
        Notification notification = notificationRepository.findById(notificationId)
            .orElseThrow(() -> new RuntimeException("Notification not found"));

        // Security check — only owner or role match can mark as read
        if (!notification.getRecipientUserId().equals(userId)
                && notification.getTargetRole() == null) {
            throw new RuntimeException("Access denied");
        }

        notification.setRead(true);
        notificationRepository.save(notification);
        return toDto(notification);
    }

    // Mark ALL notifications as read for a user
    public void markAllAsRead(String userId, String role) {
        // Personal notifications
        List<Notification> personal = notificationRepository
            .findByRecipientUserIdAndReadFalseOrderByCreatedAtDesc(userId);
        personal.forEach(n -> n.setRead(true));
        notificationRepository.saveAll(personal);

        // Role-based notifications
        List<Notification> roleBased = notificationRepository
            .findByTargetRoleAndReadFalseOrderByCreatedAtDesc(role);
        roleBased.forEach(n -> n.setRead(true));
        notificationRepository.saveAll(roleBased);
    }

    // Delete a single notification
    public void deleteNotification(String notificationId, String userId) {
        Notification notification = notificationRepository.findById(notificationId)
            .orElseThrow(() -> new RuntimeException("Notification not found"));

        if (!notification.getRecipientUserId().equals(userId)) {
            throw new RuntimeException("Access denied");
        }
        notificationRepository.delete(notification);
    }

    // Delete all notifications for a user
    public void deleteAll(String userId) {
        notificationRepository.deleteAllByRecipientUserId(userId);
    }

    // Create a notification generated by the client (frontend)
    public NotificationResponse createClientNotification(String userId, com.smartcampus.dto.request.ClientNotificationRequest request) {
        // Fallback to SYSTEM_ANNOUNCEMENT or something safe if the type isn't standard
        NotificationType type;
        try {
            type = NotificationType.valueOf(request.getType().toUpperCase());
        } catch (IllegalArgumentException e) {
            type = NotificationType.SYSTEM_ANNOUNCEMENT; // default fallback
        }

        Notification notification = Notification.builder()
            .recipientUserId(userId)
            .type(type)
            .title(request.getTitle())
            .message(request.getMessage())
            .relatedEntityType("CLIENT")
            .build();

        notificationRepository.save(notification);
        return toDto(notification);
    }

    public ManagerBroadcastNoticeResponse sendManagerBroadcastNotice(User actor, ManagerBroadcastNoticeRequest request) {
        if (actor.getRole() != Role.MANAGER && actor.getRole() != Role.ADMIN) {
            throw new RuntimeException("Only managers or admins can send broadcast notices");
        }

        String title = String.valueOf(request.getTitle() == null ? "" : request.getTitle()).trim();
        String message = String.valueOf(request.getMessage() == null ? "" : request.getMessage()).trim();
        if (title.isBlank() || message.isBlank()) {
            throw new IllegalArgumentException("Title and message are required");
        }

        LocalDateTime windowStart = request.getWindowStart() != null ? request.getWindowStart() : LocalDateTime.now();
        LocalDateTime windowEnd = request.getWindowEnd() != null ? request.getWindowEnd() : windowStart.plusDays(14);
        if (windowEnd.isBefore(windowStart)) {
            throw new IllegalArgumentException("Window end must be after window start");
        }

        String query = String.valueOf(request.getResourceQuery() == null ? "" : request.getResourceQuery()).trim().toLowerCase(Locale.ROOT);

        List<Booking> bookingsInWindow = findUpcomingBookingsInWindow(windowStart, windowEnd);
        List<Booking> matchedBookings = query.isBlank()
            ? bookingsInWindow
            : filterBookingsByResourceQuery(bookingsInWindow, query);

        Set<String> userIds = matchedBookings.stream()
            .map(Booking::getUser)
            .filter(Objects::nonNull)
            .map(User::getId)
            .filter(id -> id != null && !id.isBlank())
            .collect(Collectors.toCollection(HashSet::new));

        List<Notification> notifications = new ArrayList<>();
        for (String userId : userIds) {
            notifications.add(Notification.builder()
                .recipientUserId(userId)
                .type(NotificationType.SYSTEM_ANNOUNCEMENT)
                .title(title)
                .message(message)
                .relatedEntityType("BROADCAST_NOTICE")
                .relatedEntityId(actor.getId())
                .build());
        }

        if (!notifications.isEmpty()) {
            notificationRepository.saveAll(notifications);
        }

        create(Notification.builder()
            .recipientUserId(actor.getId())
            .type(NotificationType.SYSTEM_ANNOUNCEMENT)
            .title("Broadcast Sent")
            .message("Your notice was sent to " + userIds.size() + " users.")
            .relatedEntityType("BROADCAST_NOTICE")
            .build());

        return ManagerBroadcastNoticeResponse.builder()
            .title(title)
            .resourceQuery(request.getResourceQuery())
            .windowStart(windowStart)
            .windowEnd(windowEnd)
            .matchedBookings(matchedBookings.size())
            .notifiedUsers(userIds.size())
            .build();
    }

    // ================================================================
    //  NOTIFICATION TRIGGER METHODS
    //  These are called from other services to create notifications
    // ================================================================

    // ─── Welcome notification ─────────────────────────────────────────
    // Called from: AuthService.register()
    public void sendWelcomeNotification(String userId, String userName) {
        create(Notification.builder()
            .recipientUserId(userId)
            .type(NotificationType.WELCOME)
            .title("Welcome to Smart Campus! 🎓")
            .message("Hi " + userName + "! Your account is ready. "
                + "You can now book resources and report incidents.")
            .relatedEntityType("USER")
            .build());
    }

    // ─── Role change notification ──────────────────────────────────────
    // Called from: AdminService.updateRole()
    public void sendRoleChangedNotification(String userId, String newRole) {
        String message = switch (newRole) {
            case "ADMIN"      -> "You have been granted System Administrator access. "
                                + "2FA setup required on next login.";
            case "TECHNICIAN" -> "You have been assigned the Technician role. "
                                + "You can now manage maintenance tickets. "
                                + "2FA setup required on next login.";
            case "MANAGER"    -> "You have been assigned the Manager role. "
                                + "2FA setup required on next login.";
            default           -> "Your account role has been updated to " + newRole + ".";
        };

        create(Notification.builder()
            .recipientUserId(userId)
            .type(NotificationType.ROLE_CHANGED)
            .title("Your role has been updated")
            .message(message)
            .relatedEntityType("USER")
            .build());
    }

    // ─── Account status notification ──────────────────────────────────
    // Called from: AdminService.toggleUserStatus()
    public void sendAccountStatusNotification(String userId, boolean enabled) {
        create(Notification.builder()
            .recipientUserId(userId)
            .type(enabled ? NotificationType.ACCOUNT_ENABLED
                          : NotificationType.ACCOUNT_DISABLED)
            .title(enabled ? "Account Enabled" : "Account Disabled")
            .message(enabled
                ? "Your account has been re-enabled. You can now log in."
                : "Your account has been disabled. Contact an administrator.")
            .relatedEntityType("USER")
            .build());
    }

    // ================================================================
    //  MODULE B — BOOKING NOTIFICATIONS
    // ================================================================

    public void sendBookingCreatedNotifications(User actor, String bookingId, String resourceName) {
        // Notifies User
        create(Notification.builder()
            .recipientUserId(actor.getId())
            .type(NotificationType.BOOKING_CREATED)
            .title("Booking Requested")
            .message("You requested to book " + resourceName + ". Pending approval.")
            .relatedEntityId(bookingId)
            .relatedEntityType("BOOKING")
            .build());

        // Notifies Admins
        create(Notification.builder()
            .targetRole("ADMIN")
            .type(NotificationType.BOOKING_CREATED)
            .title("New Booking Request")
            .message(actor.getName() + " requested to book " + resourceName + ".")
            .relatedEntityId(bookingId)
            .relatedEntityType("BOOKING")
            .build());

        // Notifies Managers
        create(Notification.builder()
            .targetRole("MANAGER")
            .type(NotificationType.BOOKING_CREATED)
            .title("New Booking Request")
            .message(actor.getName() + " requested to book " + resourceName + ".")
            .relatedEntityId(bookingId)
            .relatedEntityType("BOOKING")
            .build());
    }

    public void sendBookingDecisionNotifications(User actor, String ownerId, String bookingId, String resourceName, boolean approved, String reason) {
        NotificationType type = approved ? NotificationType.BOOKING_APPROVED : NotificationType.BOOKING_REJECTED;
        String title = approved ? "Booking Approved ✓" : "Booking Rejected";
        String messageToOwner = approved 
            ? "Your booking for " + resourceName + " has been approved." 
            : "Your booking for " + resourceName + " was rejected. Reason: " + reason;

        // Notify Owner
        create(Notification.builder()
            .recipientUserId(ownerId)
            .type(type)
            .title(title)
            .message(messageToOwner)
            .relatedEntityId(bookingId)
            .relatedEntityType("BOOKING")
            .build());

        // Notify Actor (Admin/Manager) confirmation
        create(Notification.builder()
            .recipientUserId(actor.getId())
            .type(type)
            .title("Action Confirmed")
            .message("You " + (approved ? "approved" : "rejected") + " the booking for " + resourceName + ".")
            .relatedEntityId(bookingId)
            .relatedEntityType("BOOKING")
            .build());
    }

    public void sendBookingCancelledNotifications(User actor, String bookingId, String resourceName) {
        // Notifies Admins
        create(Notification.builder()
            .targetRole("ADMIN")
            .type(NotificationType.BOOKING_CANCELLED)
            .title("Booking Cancelled")
            .message(actor.getName() + " cancelled their booking for " + resourceName + ".")
            .relatedEntityId(bookingId)
            .relatedEntityType("BOOKING")
            .build());

        // Notifies Managers
        create(Notification.builder()
            .targetRole("MANAGER")
            .type(NotificationType.BOOKING_CANCELLED)
            .title("Booking Cancelled")
            .message(actor.getName() + " cancelled their booking for " + resourceName + ".")
            .relatedEntityId(bookingId)
            .relatedEntityType("BOOKING")
            .build());

        // Notifies User Self
        create(Notification.builder()
            .recipientUserId(actor.getId())
            .type(NotificationType.BOOKING_CANCELLED)
            .title("Booking Cancelled")
            .message("You cancelled the booking for " + resourceName + ".")
            .relatedEntityId(bookingId)
            .relatedEntityType("BOOKING")
            .build());
    }

    // ================================================================
    //  MODULE C — TICKET NOTIFICATIONS
    // ================================================================

    public void sendTicketCreatedNotifications(User creator, String ticketId, String category, String priority) {
        // User (self)
        create(Notification.builder()
            .recipientUserId(creator.getId())
            .type(NotificationType.TICKET_CREATED)
            .title("Incident Reported")
            .message("You successfully reported a " + category + " issue.")
            .relatedEntityId(ticketId)
            .relatedEntityType("TICKET")
            .build());

        // Admins
        create(Notification.builder()
            .targetRole("ADMIN")
            .type(NotificationType.TICKET_CREATED)
            .title("New Incident [" + priority + "]")
            .message(creator.getName() + " reported a " + category + " issue.")
            .relatedEntityId(ticketId)
            .relatedEntityType("TICKET")
            .build());

        // Managers
        create(Notification.builder()
            .targetRole("MANAGER")
            .type(NotificationType.TICKET_CREATED)
            .title("New Incident [" + priority + "]")
            .message(creator.getName() + " reported a " + category + " issue.")
            .relatedEntityId(ticketId)
            .relatedEntityType("TICKET")
            .build());
    }

    public void sendTicketAssignedNotifications(User actor, String technicianId, String ticketOwnerId, String ticketId, String category) {
        // Technician
        create(Notification.builder()
            .recipientUserId(technicianId)
            .type(NotificationType.TICKET_ASSIGNED)
            .title("Ticket Assigned To You")
            .message("You have been assigned a " + category + " incident ticket.")
            .relatedEntityId(ticketId)
            .relatedEntityType("TICKET")
            .build());

        // User
        create(Notification.builder()
            .recipientUserId(ticketOwnerId)
            .type(NotificationType.TICKET_ASSIGNED)
            .title("Ticket Assigned")
            .message("A technician has been assigned to your " + category + " ticket.")
            .relatedEntityId(ticketId)
            .relatedEntityType("TICKET")
            .build());

        // Admin/Manager (Self)
        create(Notification.builder()
            .recipientUserId(actor.getId())
            .type(NotificationType.TICKET_ASSIGNED)
            .title("Assignment Confirmed")
            .message("You assigned the " + category + " ticket.")
            .relatedEntityId(ticketId)
            .relatedEntityType("TICKET")
            .build());
    }

    public void sendTicketStatusUpdatedNotifications(User actor, String ticketOwnerId, String technicianId, String ticketId, String oldStatus, String newStatus) {
        // Regardless of who did it, we notify standard parties.
        Role role = actor.getRole();

        // 1. Notify User (if actor != user)
        if (!actor.getId().equals(ticketOwnerId)) {
            create(Notification.builder()
                .recipientUserId(ticketOwnerId)
                .type(NotificationType.TICKET_STATUS_UPDATED)
                .title("Ticket Status Updated")
                .message("Your ticket status changed to " + newStatus + ".")
                .relatedEntityId(ticketId)
                .relatedEntityType("TICKET")
                .build());
        }

        // 2. Notify Admin/Manager if Technician updated it
        if (role == Role.TECHNICIAN) {
            create(Notification.builder()
                .targetRole("ADMIN")
                .type(NotificationType.TICKET_STATUS_UPDATED)
                .title("Ticket Updated")
                .message("A technician updated ticket to " + newStatus)
                .relatedEntityId(ticketId)
                .relatedEntityType("TICKET")
                .build());

            create(Notification.builder()
                .targetRole("MANAGER")
                .type(NotificationType.TICKET_STATUS_UPDATED)
                .title("Ticket Updated")
                .message("A technician updated ticket to " + newStatus)
                .relatedEntityId(ticketId)
                .relatedEntityType("TICKET")
                .build());
        }

        // 3. Notify Technician if Admin/Manager updated it
        if ((role == Role.ADMIN || role == Role.MANAGER) && technicianId != null && !actor.getId().equals(technicianId)) {
            create(Notification.builder()
                .recipientUserId(technicianId)
                .type(NotificationType.TICKET_STATUS_UPDATED)
                .title("Assigned Ticket Updated")
                .message("An administrator changed the status of your assigned ticket to " + newStatus)
                .relatedEntityId(ticketId)
                .relatedEntityType("TICKET")
                .build());
        }

        // 4. Notify Actor (Self Confirmation)
        create(Notification.builder()
            .recipientUserId(actor.getId())
            .type(NotificationType.TICKET_STATUS_UPDATED)
            .title("Update Confirmed")
            .message("You updated the ticket to " + newStatus)
            .relatedEntityId(ticketId)
            .relatedEntityType("TICKET")
            .build());
    }

    public void sendCommentAddedNotifications(User actor, String ticketOwnerId, String technicianId, String ticketId) {
        String actorId = actor.getId();

        // Notify Admin
        if (actor.getRole() != Role.ADMIN) {
            create(Notification.builder()
                .targetRole("ADMIN")
                .type(NotificationType.TICKET_COMMENT_ADDED)
                .title("New Comment")
                .message(actor.getName() + " added a comment to a ticket.")
                .relatedEntityId(ticketId)
                .relatedEntityType("TICKET")
                .build());
        }

        // Notify Manager
        if (actor.getRole() != Role.MANAGER) {
            create(Notification.builder()
                .targetRole("MANAGER")
                .type(NotificationType.TICKET_COMMENT_ADDED)
                .title("New Comment")
                .message(actor.getName() + " added a comment to a ticket.")
                .relatedEntityId(ticketId)
                .relatedEntityType("TICKET")
                .build());
        }

        // Notify User (Owner)
        if (!actorId.equals(ticketOwnerId)) {
            create(Notification.builder()
                .recipientUserId(ticketOwnerId)
                .type(NotificationType.TICKET_COMMENT_ADDED)
                .title("New Comment on Your Ticket")
                .message(actor.getName() + " added a comment.")
                .relatedEntityId(ticketId)
                .relatedEntityType("TICKET")
                .build());
        }

        // Notify Technician
        if (technicianId != null && !actorId.equals(technicianId)) {
            create(Notification.builder()
                .recipientUserId(technicianId)
                .type(NotificationType.TICKET_COMMENT_ADDED)
                .title("New Comment")
                .message(actor.getName() + " added a comment to your assigned ticket.")
                .relatedEntityId(ticketId)
                .relatedEntityType("TICKET")
                .build());
        }
    }

    // ================================================================
    //  INTERNAL HELPERS
    // ================================================================

    // Save a notification to DB
    private void create(Notification notification) {
        notificationRepository.save(notification);
        log.info("Notification created: type={}, recipient={}, role={}",
            notification.getType(),
            notification.getRecipientUserId(),
            notification.getTargetRole());
    }

    // Convert entity to DTO
    private NotificationResponse toDto(Notification n) {
        return NotificationResponse.builder()
            .id(n.getId())
            .type(n.getType().name())
            .title(n.getTitle())
            .message(n.getMessage())
            .relatedEntityId(n.getRelatedEntityId())
            .relatedEntityType(n.getRelatedEntityType())
            .read(n.isRead())
            .createdAt(n.getCreatedAt())
            .build();
    }

    public void sendTicketUpdatedNotifications(User actor, String ticketId, String category) {
        // User (Self Confirmation)
        create(Notification.builder()
            .recipientUserId(actor.getId())
            .type(NotificationType.TICKET_UPDATED)
            .title("Ticket Updated")
            .message("You updated the details for your " + category + " ticket.")
            .relatedEntityId(ticketId)
            .relatedEntityType("TICKET")
            .build());

        // Admins
        create(Notification.builder()
            .targetRole("ADMIN")
            .type(NotificationType.TICKET_UPDATED)
            .title("Ticket Details Updated")
            .message(actor.getName() + " updated details for ticket: " + category)
            .relatedEntityId(ticketId)
            .relatedEntityType("TICKET")
            .build());

        // Managers
        create(Notification.builder()
            .targetRole("MANAGER")
            .type(NotificationType.TICKET_UPDATED)
            .title("Ticket Details Updated")
            .message(actor.getName() + " updated details for ticket: " + category)
            .relatedEntityId(ticketId)
            .relatedEntityType("TICKET")
            .build());
    }

    private List<Booking> filterBookingsByResourceQuery(List<Booking> bookings, String query) {
        Set<String> resourceIds = bookings.stream()
            .map(Booking::getResourceId)
            .filter(id -> id != null && !id.isBlank())
            .collect(Collectors.toSet());

        Map<String, Resource> resourceById = new HashMap<>();
        if (!resourceIds.isEmpty()) {
            resourceRepository.findAllById(resourceIds)
                .forEach(resource -> resourceById.put(resource.getId(), resource));
        }

        return bookings.stream()
            .filter(booking -> {
                Resource resource = resourceById.get(booking.getResourceId());
                String haystack = String.join(" ",
                    safeLower(booking.getResourceName()),
                    safeLower(booking.getResourceType()),
                    safeLower(resource != null ? resource.getName() : null),
                    safeLower(resource != null ? resource.getLocation() : null),
                    safeLower(resource != null ? resource.getBuilding() : null)
                );
                return haystack.contains(query);
            })
            .collect(Collectors.toList());
    }

    private String safeLower(String value) {
        return value == null ? "" : value.toLowerCase(Locale.ROOT);
    }

    private List<Booking> findUpcomingBookingsInWindow(LocalDateTime windowStart, LocalDateTime windowEnd) {
        return bookingRepository.findAll().stream()
            .filter(booking -> booking.getStatus() == BookingStatus.APPROVED || booking.getStatus() == BookingStatus.PENDING)
            .filter(booking -> booking.getStartTime() != null && booking.getEndTime() != null)
            .filter(booking -> !booking.getEndTime().isBefore(windowStart) && !booking.getStartTime().isAfter(windowEnd))
            .collect(Collectors.toList());
    }
}