spring.application.name=smart-campus-api

# Server
server.port=8083

# MongoDB
spring.mongodb.uri=mongodb+srv://sisithaindumin:1234@cluster0.s4q0qc8.mongodb.net/smart_campus_db?appName=Cluster0
spring.mongodb.database=smart_campus_db

# JWT
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=190689468971-dbn97mebs1joon3mvu1ij794ur2dmni5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8083/login/oauth2/code/google

# Frontend URL (used in OAuth2 redirect after login)
app.frontend-url=http://localhost:5173

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:5175